# Generated by Django 4.2.15 on 2024-10-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
