# Generated by Django 4.2.15 on 2024-11-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='No description', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.TextField(default='No keywords'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
