
# Generated by Django 5.1.2 on 2024-10-20 18:47


import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='documents/'),
        ),
    ]
