# Generated by Django 5.1.3 on 2024-11-18 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0005_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserProfile',
        ),
        migrations.RenameField(
            model_name='customuserprofile',
            old_name='is_pma',
            new_name='is_pma_admin',
        ),
    ]
