# Generated by Django 5.1.3 on 2024-12-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpage', '0007_accessrequest'),
        ('projectpage', '0007_project_description_comment'),
    ]

    operations = [
    ]
